### ISSUE TITLE
Envio trabalho - Compilador de Brainf_ck

### ISSUE THREAD

**Issue by fabiolamfleury** [fabiommendes/compiladores#11]
https://github.com/fabiolamfleury/Brainf_ck-compiler

Fabíola Malta Fleury - 150009275

Josué Nascimento da Silva - 150038933

**Comment by Ronyell** [comment]
https://github.com/thiagonf/Compiladores_Trabalho2

Ronyel Henrique dos Santos - 150046073

Thiago Nogueira Freire - 150047142

**Comment by rodrigocam** [comment]
https://github.com/pablodiegoss/brainfuck_compiler

Rodrigo Oliveira Campos - 150021399
Pablo Diego Silva da Silva - 150019475

**Comment by joaopaulonsoares** [comment]
https://github.com/joaopaulonsoares/Compiladores_02-brainf_ck

João Paulo Nunes Soares - 150038267

**Comment by luishng** [comment]
[Luis Henrique Nunes Guimarães - 13/0122971](https://github.com/luishng/BrainF-k)

**Comment by SabinoGs** [comment]
[Repositório - T1](https://github.com/SabinoGs/compiladores)
Gustavo Sabino  - 13/0009997
Macário Soares - 11/0016459

**Comment by Diego-BF** [comment]
https://github.com/Diego-BF/brainf_ck_compiler
- Diego França - 14/0136355
- João Pedro Sconetto - 14/0145940

**Comment by hpe95** [comment]
https://github.com/peddrro/Brainf_ck_compiler

- Felipe Osorio - 140138676

- Harrison Pedro - 140142801

**Comment by navarrovmn** [comment]
https://github.com/Hargre/brainfuck-to-c

* Felipe de Oliveira Hargreaves - 15/0009313
* Victor Matias Navarro - 14/0032932

**Comment by danielmarquesr** [comment]
https://github.com/FilipeKN4/Compilador_Brainf_ck_trabalho_01

- Filipe Coelho Hilário Barcelos 15/0059213
- Daniel Marques Rangel 15/0008228

**Comment by miguelpimentel** [comment]
https://github.com/miguelpimentel/brainfuck_compiler

* João Guilherme Silva de Meneses de Paula - 13/0011126
* Miguel Pimentel - 14/0156143

**Comment by leticiadesouza** [comment]
https://github.com/drianne/brainfuck

- Adrianne Alves da Silva - 16/0047595
- Letícia de Souza Santos - 150015160

**Comment by guilacerda** [comment]
https://github.com/guilacerda/Brainf_ck-Compiler

* Guilherme Guimarães Lacerda - 15/0128282
* Matheus Miranda Lacerda - 14/0056793

**Comment by stebezs** [comment]
https://github.com/stebezs/Compilador_brainF-k

* Matheus de Oliveira - 14/0028331
* Stefânia Bezerra - 14/0031634

**Comment by Rdadamos** [comment]
[02-brainf_ck](https://github.com/Rdadamos/compiladores-trabalhos/tree/master/02-brainf_ck)
- Halê Valente Silva - 13/0010014
- Rodrigo Dadamos Lopes da Silva - 15/0064535

**Comment by guiaugusto** [comment]
https://github.com/guiaugusto/tradutor_bf

- Bruna Pinos de Oliveira - 15/0119984
- Guilherme Augusto Nunes Silva - 15/0128134

**Comment by hugonxc** [comment]
https://github.com/hugonxc/go_fck_compiler

- Hugo Neves de Carvalho - 15/0011792

**Comment by Geovannioj** [comment]
[brain_f*uckCompiler](https://github.com/Geovannioj/brain_f-ckCompilerToC)  
Geovanni Oliveira 12/0119056
