### ISSUE TITLE
Interpretador para Lispf_ck

### ISSUE THREAD

**Issue by drianne** [fabiommendes/compiladores#14]
https://github.com/drianne/Lispf_ck-interpreter.git
Adrianne Alves da Silva 160047595
Leticia de Souza 150015160

**Comment by FilipeKN4** [comment]
https://github.com/danielmarques28/lisp-f_ck_trab04
- Filipe Coelho Hilário Barcelos 15/0059213
- Daniel Marques Rangel 15/0008228

**Comment by guilacerda** [comment]
https://github.com/guilacerda/lispf_ck_interpreter

* Guilherme Guimaraẽs Lacerda 15/0128282
* Matheus Miranda Lacerda 14/0056793

**Comment by guiaugusto** [comment]
https://github.com/guiaugusto/lispf_ck-interpreter
- Bruna Pinos de Oliveira - 15/0119984
- Guilherme Augusto Nunes Silva - 15/0128134

**Comment by navarrovmn** [comment]
https://github.com/navarrovmn/lispfuck-interpreter

* Felipe Hargreaves - 150009313
* Victor Navarro - 140032932
* A árvore sintática que o interpretador consome foi construída através de uma pequena adaptação do parser construído pelas alunas Adrianne Alves e Letícia de Souza. Agradecemos às alunas.

**Comment by joaopaulonsoares** [comment]
https://github.com/joaopaulonsoares/Interpretador_LispF_ck_Trab04

 * João Paulo Nunes Soares  15/0038267

 * Ronyell Henrique dos Santos 15/0046073

 * Thiago Nogueira Freire 15/0047142

**Comment by luishng** [comment]
https://github.com/luishng/Lispf_ck

Felipe Osorio - 140138676

Harrison Pedro - 140142801

Luis Henrique - 130122971

**Comment by fabiolamfleury** [comment]
https://github.com/fabiolamfleury/lispf_ck-interpreter

Fabíola Malta Fleury - 150009275

Josué Nascimento da Silva - 150038933

**Comment by joaaogui** [comment]
https://github.com/joaaogui/lispfuck_lexer-parser

João Guilherme Silva de Meneses de Paula - 13/0011126
Miguel Pimentel - 14/0156143

**Comment by halevalente** [comment]
https://github.com/halevalente/lispfck_interpreter

Halê Valente Silva - 13/0010014
Geovanni Oliveira de Jesus - 12/0119056

**Comment by hugonxc** [comment]
https://github.com/hugonxc/lisp_f_ck_interpreter

- Hugo Neves de Carvalho - 15/0011792

**Comment by Diego-BF** [comment]
https://github.com/sconetto/lispf_ck-interpreter

- João Pedro Sconetto - 14/0145940

- Diego França - 14/0136355
