### ISSUE TITLE
Envio Trabalho - Compilador de Lispf_ck

### ISSUE THREAD

**Issue by guilacerda** [fabiommendes/compiladores#15]
https://github.com/MatheusMiranda/lispf_ck_compilator

* Guilherme Guimaraẽs Lacerda 15/0128282
* Matheus Miranda Lacerda 14/0056793

OBS: O parser utilizado foi o dos alunos Guilherme Augusto e Bruna Pinos, disponível no seguinte repositório: github.com/guiaugusto/lispf_ck-interpreter/blob/master/interpreter-lispf_ck.py

**Comment by Hargre** [comment]
https://github.com/Hargre/lispfuck-to-brainfuck

* Felipe de Oliveira Hargreaves - 15/00009313
* Victor Navarro - 14/0032932

A árvore sintática que o compilador consome foi construída através de uma pequena adaptação do parser construído pelas alunas Adrianne Alves e Letícia de Souza. Agradecemos às alunas.

**Comment by guiaugusto** [comment]
https://github.com/brunapinos/compiler_lispfk

- Bruna Pinos de Oliveira - 15/0119984
- Guilherme Augusto Nunes Silva - 15/0128134

**Comment by fabiolamfleury** [comment]
https://github.com/fabiolamfleury/lispf_ck-compiler

Fabíola Malta Fleury - 150009275

Josué Nascimento da Silva - 150038933

**Comment by thiagonf** [comment]
https://github.com/thiagonf/Compiladores_Trabalho_5

- João Paulo Nunes Soares 15/0038267

- Ronyell Henrique dos Santos 15/0046073

- Thiago Nogueira Freire 15/0047142

**Comment by drianne** [comment]
https://github.com/drianne/Lispf_ck_compiler.git

- Adrianne Alves da Silva  16/0047595 

- Letícia de Souza  15/0015160

**Comment by danielmarquesr** [comment]
https://github.com/FilipeKN4/Compilador_Lispf_ck_trabalho_05

- Daniel Marques Rangel 15/0008228

- Filipe Coelho Hilário Barcelos 15/0059213

**Comment by miguelpimentel** [comment]
https://github.com/joaaogui/lispfuck_lexer-parser

João Guilherme Silva de Meneses de Paula - 13/0011126
Miguel Pimentel - 14/0156143

**Comment by Geovannioj** [comment]
https://github.com/Geovannioj/compiler_lisp_fck
Geovanni Oliveira de Jesus
12/0119056
