### ISSUE TITLE
Matéria da prova

### ISSUE THREAD

**Issue by RomeuCarvalhoAntunes** [fabiommendes/compiladores#2]
Professor, gostaria de saber qual vai ser a matéria da primeira prova, que está no plano, planejada para o dia 28. Desde já, grato.

**Comment by vital-edu** [comment]
@fabiommendes acho que seria muito importante passar os tópicos que devemos focar para a prova além de alguma atividade preparatória para a prova.

**Comment by fabiommendes** [comment]
Matéria:

* Análise léxica
* Expressões regulares e linguagens regulares
* Análise sintática
* Notação BNF
* Árvores sintáticas
* Expressões S

Estou preparando uma lista baseada no Dragon Book e envio ainda hoje.

**Comment by fabiommendes** [comment]
Exercícios sugeridos.

Estou me baseando na segunda edição do Dragon Book (Compiladores: Princípios, Técnicas e Ferramentas, Aho, Sethi, Ullman). Vamos dividir o livro e a leitura em capítulos:

**Capítulo 1** 
Visão geral, vale a pena ler, mas não tem nenhum exercício.

**Capítulo 2**
Seções: 2.1, 2.2, 2.4, 2.6
Exercícios: 1, 2, 3, 4, 5, 6, 14, 16a, 16b

**Capítulo 3**
Seções: 3.1, 3.3
Exercícios: 1, 2 (p/ C, Python e JS), 3b, 6, 7, 8, 9

**Capítulo 4**
Seções: 4.1, 4.2, 4.3, 4.4
Exercícios: 1, 2, 3, 4, 5, 6,
