### ISSUE TITLE
Grupo Ox

### ISSUE THREAD

**Issue by fabiommendes** [fabiommendes/compiladores#3]
Por favor inclua o nome, matrícula e usuário do github de todos os integrantes do grupo.

**Comment by navarrovmn** [comment]
Membros do grupo Ox:

| Nome | Matrícula | Github |
| :------: | :-----------: | :-------: |
| Ateldy Borges Brasil Filho | 15/0006101 | ateldyfilho |
| Bruna Pinos de Oliveira | 15/0119984 | brunapinos |
| Felipe de Oliveira Hargreaves | 15/0009313 | Hargre |
| Guilherme Augusto Nunes Silva | 15/0128134 | guiaugusto |
| Guilherme Guimarães Lacerda | 15/0128282 | Guilacerda |
| Letícia de Souza Santos | 15/0015160 | leticiadesouza |
| Matheus Miranda Lacerda | 14/0056793 | MatheusMiranda |
| Victor Matias Navarro | 14/0032932 | navarrovmn |

**Comment by fabiommendes** [comment]
Backlog:

* [ ] Criar classe para representar nós na árvore sintática a partir de um ADT
* [ ] Função para percorrer e visitar cada nó na árvore sintática
* [ ] Funções para renderizar a árvore sintática pretty print
* [ ] Classe para implementar um visitor genérico
* [ ] Classe para implementar uma renderização genérica com suporte para indentação
* [ ] Nós genéricos para Python, Js e C
* [ ] Emitir código em Python
* [ ] Emitir código em C
* [ ] Emitir código em Js

**Comment by Joranhezon** [comment]
Matheus Joranhezon, 150018428.
