### ISSUE TITLE
Grupo Bricks

### ISSUE THREAD

**Issue by fabiommendes** [fabiommendes/compiladores#4]
Por favor inclua o nome, matrícula e usuário do github de todos os integrantes do grupo.

**Comment by MarcoRLK** [comment]
Grupo Parser Bricks:


|Nome|Matricula|GitHub|
|:-------:|:----------:|:-------:|
|Macario Soares|11/0016459|MacSoares|
|Gustavo Sabino|13/0009997|Sabinogs|
|Halê Valente Silva|13/0010014|halevalente|
|Geovanni Oliveira|12/0119056|GeovanniOj|
|Ulysses Lara|13/0136026|ulyssesBML|
|Anderson Silva|14/0130004|andersonms1|
|Marco Kuroiva|16/0160464|MarcoRLK|
|Daniel Marques|15/0008228|danielmarques28|
|Rodrigo Dadamos|15/0064535|Rdadamos|
