### ISSUE TITLE
Grupo Sidekick

### ISSUE THREAD

**Issue by fabiommendes** [fabiommendes/compiladores#5]
Por favor inclua o nome, matrícula e usuário do github de todos os integrantes do grupo.

**Comment by vital-edu** [comment]
| Nome | Matrícula | Github |
|-------|----------|---------|
| Arthur José Benedito de Oliveira Assis | 150030894 | @arthur0496 |
| Diego Barbosa da Mota França | 140136355 | @Diego-BF |
| Eduardo Vital Alencar Cunha | 130008419 | @vital-edu |
| João Guilherme Silva de Meneses de Paula | 130011126 | @joaaogui |
| João Pedro Sconetto | 140145940 | @sconetto |
| Miguel Pimentel | 140156143 | @miguelpimentel |
| Wesley Pereira Araujo | 130039217 | @wparaujo |
| Wilton da Silva Rodrigues | 130049212| @wiltonsr |

**Comment by fabiommendes** [comment]
Oi pessoal,

Resolvi separar o repositório do compilador do repositório principal do sidekick para garantir que o código fique bem desacoplado e diminuir a chance de conflitos. Já tem um esqueleto inicial inclusive com alguns testes falhando (rode pytest) na raiz do projeto. 

Procurem em "fabiommendes/qlcompiler". O projeto está registrado no pip e na medida que vocês forem atualizando subo as releases. Assim fica fácil distribuir e instalar em outras máquinas.

**Comment by fabiommendes** [comment]
Backlog proposto:

* [ ] Emitir código para Python convertendo as quick lambdas em lambdas normais
* [ ] Emitir código javascript (talvez dando a opção para o usuário utilizar os lambdas do ES6).
* [ ] Emitir código para C
* [ ] Inspecionar código Js para verificar funções Python que possuam um correspondente em javascript
* [ ]  Criar um pequeno runtime javascript com funções que replicam funcionalidade do Python. Focar apenas nas funções mais comuns.
*  [ ] Criar um runtime C que faça o mesmo
*  [ ] Inferência de tipos em C
