### ISSUE TITLE
Grupo Jarbas

### ISSUE THREAD

**Issue by fabiommendes** [fabiommendes/compiladores#6]
Por favor inclua o nome, matrícula e usuário do github de todos os integrantes do grupo.

**Comment by hugonxc** [comment]
Segue abaixo os intergrantes:


<table>
    <th>Nome</th>
    <th>Matrícula</th>
    <th>Usuário</th>
   <tr>
       <td>Daniel Ashton Oda</td>
       <td>15/0008121</td>
       <td>danieloda</td> 
   </tr>
   <tr>
       <td>Fabíola Malta Fleury</td>
       <td>15/0009275</td>
       <td>fabiolamfleury</td> 
   </tr>
   <tr>
       <td>Filipe Coelho Hilário Barcelos</td>
       <td>15/0059213</td>
       <td>FilipeKN4</td> 
   </tr>
   <tr>
       <td>Hugo Neves de Carvalho</td>
       <td>15/0011792</td>
       <td>hugonxc</td> 
   </tr>
   <tr>
       <td>Joao G. Saliba</td>
       <td>15/0012934</td>
       <td>joaosaliba</td> 
   </tr>
   <tr>
       <td>Josué Nascimento da Silva</td>
       <td>15/0038933</td>
       <td>josutk</td> 
   </tr>
   <tr>
       <td>Mariana Pícolo</td>
       <td>15/0017502</td>
       <td>MarianaPicolo</td> 
   </tr>
   <tr>
       <td>Pablo Diego Silva da Silva</td>
       <td>15/0019475</td>
       <td>pablodiegoss</td> 
   </tr>
   <tr>
       <td>Rodrigo Oliveira Campos</td>
       <td>150021399</td>
       <td>rodrigocam</td> 
   </tr>


</table>

**Comment by fabiommendes** [comment]
Criei um esqueleto para o jarbas_dsl para vocês trabalharem. Deem uma olhada no repositório https://github.com/fabiommendes/jarbas_dsl 

Mudei um pouco a sintaxe da linguagem para ficar mais limpo. Vocês podem fazer sugestões, mas devemos decidir logo como será a sintaxe.

Para primeira sprint, sugiro que vocês comecem por definir os nós da árvore sintática.

**Comment by fabiommendes** [comment]
Backlog:

* [ ] Definir/criar nós da árvore sintática
* [ ] Criar funções ou métodos na classe Runner para executar estes nós
* [ ] Definir as tokens da linguagem.
* [ ] Implementar um tokenizador com uma estratégia de busca pelos nós desejados
* [ ] Implementar a gramática
* [ ]  Implementar o parser.
* [ ] Validar a árvore sintática de acordo com os filters e validators fornecidos

(Essa é uma visão geral. Talvez seja melhor vocês quebrarem em sub-items.)

**Comment by rodrigocam** [comment]
@fabiommendes na chamada de método da linguagem, o método vai pode aceitar qualquer tipo de parâmetro? Números, listas, variáveis etc?
