### ISSUE TITLE
Grupo Questions (Aiken/GIFT)

### ISSUE THREAD

**Issue by fabiommendes** [fabiommendes/compiladores#7]
Por favor inclua o nome, matrícula e usuário do github de todos os integrantes do grupo.

**Comment by stebezs** [comment]
Nome | Matricula | Git
--------- | ------ | ------
Felipe Osório de Oliveira |14/0138676|felipe72
Gabriel Dias Viana |16/0120942|GabrielDViana
Harrison Pedro Ferreira de Almeida|14/014280|peddrro
Luis Henrique Nunes Guimarães|13/0122971|luishng
Matheus de Oliveira Silva|14/0028331|MFire30
Ramon Silva Sales|14/0160205|ramonsales
Stefânia Bezerra da Silva|14/0031634|stebezs

**Comment by fabiommendes** [comment]
Preparei os repositórios em fabiommendes/gift e fabiommendes/aiken. A issue de vocês para a semana que vem é implementar um parser do formato Aiken. Deem uma olhada no arquivo src/aiken/aiken.py que já tem um início.

Os dois pacotes já estão no pip. Quando vocês quiserem eu subo as versões atualizadas.

**Comment by fabiommendes** [comment]
Backlock:

* [ ] Implementar o parser e o dumper do formato Aiken
* [ ] Aceitar objetos do tipo file e string nas duas funções
* [ ] Criar testes unitários
* [ ] Aumentar o backlog com as issues do formato GIFT

**Comment by stebezs** [comment]
Nome | Matricula | Git
--------- | ------ | ------
Luis Bruno Fidelis| 14/0169695| lbrunofidelis
