### ISSUE TITLE
Grupo Kpop

### ISSUE THREAD

**Issue by joaopaulonsoares** [fabiommendes/compiladores#8]
Membros do projeto Kpop

|               Membro              |           Matrícula          |       GitHub      |
|:---------------------------------:|:-------------------------:|:-----------------:|
|    Victor Correia de Moura    | 15/0150792  | victorcmoura |
|     Romeu Carvalho Antunes   |   15/0147554  |  RomeuCarvalhoAntunes  |
|      Vitor Falcão Costa   |  15/0151624 | vitorfhc    |
|     João Paulo Nunes Soares   | 15/0038267  | joaopaulonsoares  |
|      Thiago Nogueira Freire  |  15/0047142 | thiagonf |
|     Ronyell Henrique dos Santos   |  15/0046073 | Ronyell |
|     Lucas Malta   |  13/0122050  | lucasssm |
| Igor Gabriel Marciano Evangelista |  15/0037074  | igor-gme |

**Comment by fabiommendes** [comment]
Reorganizei o repositorio do Kpop e centralizei os parsers em src/kpop/parsers/. Usem a branch "develop" para desenvolver. Vocês podem fazer um fork e começar a implementação dos parsers.

**Comment by fabiommendes** [comment]
Backlog:

* [ ] Implementar o parser para os arquivos de saída do admixture (ver src/kpop/tests/data_examples/admixture.out)
* [ ] Implementar parser para os arquivos de entrada do Arlequin
* [ ] Implementar parser para os arquivos de saída do Arlequin

**Comment by thiagonf** [comment]
Boa tarde, professor Fábio Mendes. Segue abaixo o link do repositório onde foi realizado o parser do Arlequin para o Pandas.

https://github.com/CompilaMais/Parser
